### ISSUE TITLE
Allowing to add custom composer file to container

### ISSUE THREAD

**Issue by isreehari** [bitnami/bitnami-docker-dreamfactory#15]
Could you please allow the user to add custom composer file to container. Right now we are installing php third party composer files inside running container so we can not persist them when we spin a new container. 

Any suggestion would be helpful. 

Thanks,

Sree

**Comment by marcosbc** [comment]
Hi @isreehari, currently we do not persist the vendor directory in order to support upgrades.

However, you could always fork this container, adding custom composer dependencies by changing the `app-entrypoint.sh` script:

```
diff --git a/2/debian-9/rootfs/app-entrypoint.sh b/2/debian-9/rootfs/app-entrypoint.sh
index 14e4029..e23a009 100755
--- a/2/debian-9/rootfs/app-entrypoint.sh
+++ b/2/debian-9/rootfs/app-entrypoint.sh
@@ -8,6 +8,7 @@ print_welcome_page
 if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "httpd" ]]; then
   nami_initialize apache php libphp dreamfactory
   info "Starting dreamfactory... "
+  # Here you can install custom Composer dependencies
 fi

 exec tini -- "$@"```

Then when you build the container with `docker build`, make sure to update your docker-compose file and it should be working for you.

**Comment by isreehari** [comment]
Wow, that's really nice. Thank you.
